# Generated by Django 5.2 on 2025-04-27 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0002_remove_product_image_product_image_file_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("location", models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-id"]},
        ),
        migrations.AddField(
            model_name="vendor",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vendors",
                to="marketplace.warehouse",
            ),
        ),
    ]
