# Generated by Django 5.2 on 2025-04-27 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0003_warehouse_alter_product_options_vendor_warehouse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="warehouse",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vendors",
                to="marketplace.warehouse",
            ),
            preserve_default=False,
        ),
    ]
